# Generated by Django 5.2.5 on 2025-08-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_category_sort_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='invoice',
            new_name='receipt',
        ),
    ]
